name:                aoc22
version:             0.1.0.0
github:              "rssbrrw/aoc22"
license:             BSD3
author:              "rssbrrw"
maintainer:          "rssbrrw@gmail.com"
copyright:           "2022 rssbrrw"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rssbrrw/aoc22#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  01:
    main:                Main.hs
    source-dirs:         days/01
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc22
    - split
    
  02:
    main:                Main.hs
    source-dirs:         days/02
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc22
    - split

  03:
    main:                Main.hs
    source-dirs:         days/03
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc22
    - split

  04:
    main:                Main.hs
    source-dirs:         days/04
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc22
    - split

  05:
    main:                Main.hs
    source-dirs:         days/05
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc22
    - containers
    - split

  06:
    main:                Main.hs
    source-dirs:         days/06
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc22
    - containers
    - split

  07:
    main:                Main.hs
    source-dirs:         days/07
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc22
    - split
    - containers

  08:
    main:                Main.hs
    source-dirs:         days/08
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc22
    - matrix
    - vector

  09:
    main:                Main.hs
    source-dirs:         days/09
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc22
    - containers
    - split